### ISSUE TITLE
本地运行example 下项目会报错

### ISSUE THREAD

**Issue by edsion11** [SyMind/tarojs-plugin-platform-nextjs#6]
整体步骤：
```bash
1. clone项目
2. yarn
3. lerna run build
4. cd examples/data-fetch
5. yarn dev:nextjs
```

![image](https://user-images.githubusercontent.com/56592159/183873018-ccb55077-8de7-40ba-841a-5894d001c243.png)

```bash
yarn version -- 1.22.17
lerna version -- 5.1.8
```
浏览器不能访问以nextjs为目标构建的项目，h5正常

**Comment by SyMind** [comment]
examples 目录下都是独立的项目，需要单独执行命令安装依赖 `yarn install`。

**Comment by edsion11** [comment]
谢谢～可以了
